//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailshops_bkp
    {
        public int Shop_Id { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_ImageURL { get; set; }
        public string Postcode { get; set; }
        public string Address { get; set; }
        public string Available { get; set; }
    }
}
