//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public float Weight { get; set; }
        public Nullable<int> Standard_StandardId { get; set; }
    
        public virtual Standard Standard { get; set; }
    }
}
